
# AUTOMATION

- id: motion_event_end_notify
  alias: 'motion_event_end_notify'
  initial_state: 'on'
  trigger:
    - platform: mqtt
      topic: 'motion/+/+/event/end'
  condition:
    condition: template
    value_template: >
      {{ is_state('input_boolean.motion_event_notify','on') }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          Motion {{ trigger.payload_json.camera }} camera
        notification_id: >
          {{ trigger.payload_json.device }}
        message: >-
          Detected {{ trigger.payload_json.elapsed }} seconds ({{trigger.payload_json.images|length}} frames) on
          {{ trigger.payload_json.date|int|timestamp_custom("%a %b %d @ %I:%M %p") | default(null) }}

- id: motion_camera_status_notify
  alias: 'motion_camera_status_notify'
  initial_state: 'on'
  trigger:
    - platform: mqtt
      topic: 'motion/+/+/status/+'
  condition:
    condition: template
    value_template: >
      {{ is_state('input_boolean.motion_status_notify','on') }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          Camera {{ trigger.payload_json.camera }} {{ trigger.payload_json.status }}
        notification_id: >
          {{ trigger.payload_json.device }}
        message: >-
          Camera {{ trigger.payload_json.camera }} on device {{ trigger.payload_json.device }} {{ trigger.payload_json.status }} at
          {{ trigger.payload_json.time|int|timestamp_custom("%a %b %d @ %I:%M %p") | default(null) }}

- id: motion_camera_network_status_notify
  alias: 'motion_camera_network_status_notify'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - group.motion_camera_network_status
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >
          {{ is_state('input_boolean.motion_status_notify','on') }}
      - condition: template
        value_template: >
          {{ (trigger.from_state != None) and ((trigger.from_state.state|lower) != "unknown") and (trigger.to_state.state != trigger.from_state.state) }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          {{ state_attr(trigger.entity_id,"friendly_name") }} Status
        notification_id: >
          {{ state_attr(trigger.entity_id,"friendly_name") }}
          # {{ trigger.entity_id }}
        message: >
          {{ trigger.to_state.attributes.friendly_name }} changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}

