
- id: internet_slow
  alias: internet_slow
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.internet_slow
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.internet_slow.state }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          Internet slow
        notification_id: >
          'internet_deviation'
        message: >
          At {{ states.sensor.internet_test_receive.date | timestamp_custom("%a %b %d %I:%M %p") }} the
          Internet is slow; current: {{ states.sensor.internet_test_receive.state }} Mbps;
          average {{ states.sensor.internet_receive_mean.state }} Mbps
    - service: mqtt.publish
      data_template:
        topic: 'status/internet/download'
        retain: false
        payload: >
          {{ states.sensor.internet_receive_statistics_mean.attributes }}

- id: internet_fast
  alias: internet_fast
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.internet_fast
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.internet_fast.state }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          Internet fast
        notification_id: >
          'internet_deviation'
        message: >
          At {{ states.sensor.internet_test_receive.date | timestamp_custom("%a %b %d %I:%M %p") }} the
          Internet is fast; current: {{ states.sensor.internet_test_receive.state }} Mbps;
          average {{ states.sensor.internet_receive_mean.state }} Mbps
    - service: mqtt.publish
      data_template:
        topic: 'status/internet/download'
        retain: false
        payload: >
          {{ states.sensor.internet_receive_statistics_mean.attributes }}
