exchange_api: %%HZN_EXCHANGE_API_KEY%%
exchange_auth: %%HZN_EXCHANGE_ORG%%/iamapikey
exchange_nodes: %%HZN_EXCHANGE_URL%%/orgs/%%HZN_EXCHANGE_ORG%%/nodes
exchange_status: %%HZN_EXCHANGE_URL%%/admin/status
mqtt_username: %%MQTT_USERNAME%%
mqtt_password: %%MQTT_PASSWORD%%
