title: Horizon CPU POC

views:
  - icon: mdi:chip
    id: CPU
    cards:
      - type: history-graph
        title: CPU
        refresh_interval: 10
        hours_to_show: 1 
        entities:
          - entity: sensor.cpu2msghub_cpu
            icon: mdi:arrow-up-down-bold-outline
            name: Load
          - entity: sensor.cpu2msghub_cpu_mean
            icon: mdi:heart-half-full
            name: Mean
      - type: map
        title: CPU
        aspect_ratio: 100%
        default_zoom: 1
        entities:
          - sensor.cpu2msghub_event
          - zone.home
      - type: entities
        entities:
          - entity: sensor.cpu2msghub_date
            name: When
          - entity: sensor.cpu2msghub_name
            name: Who
          - entity: sensor.cpu2msghub_cpu
            name: Load
          - entity: sensor.cpu2msghub_altitude
            name: Altitude
          - entity: sensor.cpu2msghub_latitude
            name: Latitude
          - entity: sensor.cpu2msghub_longitude
            name: Longitude
