###
### DEFAULT (replace w/ your own)
###

default_view:
  name: HOME
  view: true
  icon: mdi:home
  entities:
    - group.horizon
    - group.horizon_patterns
    - group.internet

horizon_patterns:
  view: false
  entities:
    - history_graph.sdr2msghub_sentiment
    - history_graph.cpu2msghub_cpu
  
internet:
  view: false
  entities:
    - history_graph.intranet_test
    - history_graph.internet_receive
    - history_graph.internet_send

###
### HORIZON
###

horizon:
  view: false
  entities:
    - sensor.horizon_status
    - sensor.horizon_exchange_status
    - sensor.horizon_exchange_api
    - sensor.horizon_exchange_version
    - sensor.horizon_required_minimum_exchange_version
    - sensor.horizon_preferred_exchange_version
    - sensor.horizon_architecture
    - sensor.horizon_version
    - sensor.horizon_agreement_active
    - sensor.horizon_agreements_count_active
    - sensor.horizon_agreements_count_archived
  
###
### SDR
###

sdr2msghub_view:
  name: SDR
  view: true
  icon: mdi:radio
  entities:
    - group.sdr2msghub
    - history_graph.sdr2msghub_sentiment
    - history_graph.sdr2msghub_count

sdr2msghub:
  name: sdr2msghub
  entities:
    - input_number.sdr2msghub_confidence
    - input_number.sdr2msghub_relevance
    - sensor.sdr2msghub_count
    - sensor.sdr2msghub_ratio
    - sensor.sdr2msghub_date
    - sensor.sdr2msghub_name
    - sensor.sdr2msghub_bytes
    - sensor.sdr2msghub_latitude
    - sensor.sdr2msghub_longitude
    - sensor.sdr2msghub_frequency
    - sensor.sdr2msghub_value
    - sensor.sdr2msghub_results
    - sensor.sdr2msghub_keywords
    - sensor.sdr2msghub_sentiment_label
    - sensor.sdr2msghub_sentiment_score
    - sensor.sdr2msghub_sentiment_mean
    - sensor.sdr2msghub_language
    - sensor.sdr2msghub_characters

###
### CPU
###

cpu2msghub_view:
  name: CPU
  view: true
  icon: mdi:chip
  entities:
    - group.cpu2msghub
    - history_graph.cpu2msghub_cpu
    - history_graph.cpu2msghub_count

cpu2msghub:
  name: cpu2msghub
  entities:
    - sensor.cpu2msghub_event
    - sensor.cpu2msghub_count
    - sensor.cpu2msghub_ratio
    - sensor.cpu2msghub_date
    - sensor.cpu2msghub_name
    - sensor.cpu2msghub_cpu
    - sensor.cpu2msghub_latitude
    - sensor.cpu2msghub_longitude
    - sensor.cpu2msghub_altitude
    - sensor.cpu2msghub_cpu_mean

###
### INTERNET
###
    
internet_view:
  name: INTERNET
  view: true
  icon: mdi:ip-network
  entities:
    - group.internet_details
    - group.internet_receive
    - group.internet_send
    - group.internet_automations

internet_details:
  name: Internet Details
  control: hidden
  entities:
    - binary_sensor.internet_test_state
    - sensor.internet_test
    - sensor.internet_test_ago
    - sensor.internet_count
    - sensor.internet_fast_count
    - sensor.internet_slow_count
    - input_number.internet_deviation
    - binary_sensor.internet_slow
    - binary_sensor.internet_fast
    - history_graph.internet_tests

internet_automations:
  name: internet_automations
  control: hidden
  entities:
    - automation.internet_slow
    - automation.internet_fast
    - automation.internet_slow_persistent
    - automation.internet_fast_persistent

internet_receive:
  name: internet_receive
  entities:
    - sensor.internet_test_receive
    - sensor.internet_receive_mean
    - sensor.internet_receive_min_value
    - sensor.internet_receive_max_value
    - sensor.internet_receive_standard_deviation
    - history_graph.internet_receive
    - history_graph.internet_recv_stdev

internet_send:
  name: internet_send
  entities:
    - sensor.internet_test_send
    - sensor.internet_send_mean
    - sensor.internet_send_min_value
    - sensor.internet_send_max_value
    - sensor.internet_send_standard_deviation
    - history_graph.internet_send
    - history_graph.internet_send_stdev

###
### INTRANET
###

intranet_view:
  name: INTRANET
  view: true
  icon: mdi:folder-network
  entities:
    - group.intranet_test
    - history_graph.intranet_test

intranet_test:
  name: intranet_test
  entities:
    - sensor.intranet_test
    - sensor.intranet_test_receive
    - sensor.intranet_test_send
    - sensor.intranet_receive_mean
    - sensor.intranet_receive_min_value
    - sensor.intranet_receive_max_value
    - sensor.intranet_receive_standard_deviation
    - sensor.intranet_send_mean
    - sensor.intranet_send_min_value
    - sensor.intranet_send_max_value
    - sensor.intranet_send_standard_deviation
    - sensor.intranet_test_ago
    - sensor.intranet_test_state
    - sensor.intranet_count
